apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-downward-volume
spec:
  containers:
  - image: nginx:1.15
    name: nginx
    resources: {}
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}







