apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-place
spec:
  containers:
  - image: nginx:1.15
    name: nginx
    resources: {}
    envFrom:
      - configMapRef:
          name: place-configmap
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
