apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-special
spec:
  containers:
  - image: nginx:1.15
    name: nginx
    resources: {}
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: special-config-literal
          key: special.how
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
