apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
