apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-volume
spec:
  containers:
  - image: nginx:1.15
    name: nginx
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: place-configmap
  restartPolicy: Always
status: {}
