apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: shared-path
      mountPath: /data/shared
  volumes:
  - name: shared-path
    hostPath:
      path: /tmp
      type: Directory

